plugins {
    id 'java'
    id 'application' // to run the application
    // id 'maven-publish' // to publish the application
    // id 'signing' // to sign the artifacts
    id 'com.github.johnrengelman.shadow' version '8.1.1' // to build a fat JAR
}

application {
    mainClass = 'com.uglyeagle.Main'
}

build.dependsOn shadowJar

group = 'com.uglyeagle'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}


repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.netty:netty-all:4.2.3.Final'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}


test {
    useJUnitPlatform()
}


/*
sourceSets {
    main {
        java {
            srcDirs 'src/dummy/path/src1'
            srcDirs 'src/dummy/path/src2'
        }
    }
}
*/

shadowJar {
    archiveBaseName.set('netty-server') // Set the base name
    archiveVersion.set('') // Remove the version
    archiveClassifier.set('all') // Optional: Adds '-all' to the JAR name
}

tasks.jar {
    archiveBaseName.set('netty-server') // Set the base name
    archiveVersion.set('') // Remove the version
    enabled = false
}